urlhead = 'http://www.exposomex.cn:8080/'
library(gridExtra)

#' @title Initialize ExpoMediation module
#' @description Initialize ExpoMediation module analysis. It can generate an R6
#'     class object integrating all the analysis information.
#' @usage InitMedt()
#' @details InitMedt uses R6 package to generate an R6 class object where
#'    parameters to be used for the following mediation module program are
#'    initialized and save in that object. All executed function codes in the
#'    ExpoMediaiton packaged will be recorded in the form of log text in that
#'    object. Furthermore, a program ID (i.e., PID) is randomly created for the
#'    users to identify their own program.
#' @return An R6 class object.
#' @export
#' @examples res <- InitMedt()
#' @author Mengyuan Ren, Bin Wang(corresponding author)

InitMedt = function(){
  url = paste0(urlhead,'InitMedt')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Load data file for Mediation module
#' @description Load data file for Mediation module
#' @usage LoadMedt(PID = PID, UseExample = "default", ...)
#' @param PID chr. Program ID. It must be the same with the PID generated by
#'    InitMedt.
#' @param UseExample chr. Method of uploading data. If "default"，
#'    user should upload their own data files, or use "example#1"
#'    provided by this module.
#' @param DataPath chr. Input data file directory, e.g.
#'    "D:/test/eg_Medt_data.xlsx". It should be noted that the slash
#'    symbol is "/", not "\".
#' @param VocaPath chr. Input vocabulary file directory, e.g.
#'    "D:/test/eg_Medt_data.xlsx". It should be noted that the slash
#'    symbol is "/", not "\".
#' @details LoadMedt function loads the data file and the vocabulary file into 
#'    the R6 object that InitMedt created. Noted that there are several data 
#'    format requirments for the data and vocabulary file. 
#'    For data file, the first three column must be named as "SampleID", "SubjectID" 
#'    and "Group" in sequence. The "Gourp" variable should be a character variable 
#'    to category data into two groups: "train" and "test" group. Outcome variables 
#'    should be named as "Y*". e.g., Y1, Y2, Y3... Similarly, exposure variables 
#'    should be named as "X*". e.g., X1, X2, X3..., and mediator variables should 
#'    be named as "M*". e.g., M1, M2, M3...
#'    For vocabulary file, the first column should be a character variable named 
#'    "SerialNo" indicating the names of outcome, exposure and mediator variables 
#'    in the data file. These names should be consistent with the variable names 
#'    in data file. The second column should be a character variable named "FullName" 
#'    indicating the full names (labels) of the variables. The third column should 
#'    be a character variable named "SubgroupName" indicating the groups the exposure 
#'    or mediator variables belong to.
#' @return An R6 class object containing the input data and vocabulary file.
#' @export
#' @examples res <- InitMedt()
#'    res1 <- LoadMedt(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#' @author Mengyuan Ren, Bin Wang(corresponding author)

LoadMedt =function(PID,
                   UseExample="default",
                   DataPath=NULL,
                   VocaPath=NULL){
  url = paste0(urlhead,'LoadMedt')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)
    # exdata_json = jsonlite::toJSON(exdata)
    # exdata_json = as.character(exdata_json)


    vodata = readxl::read_excel(VocaPath)
    # vodata_json = jsonlite::toJSON(vodata,dataframe = 'columns')
    # vodata_json = as.character(vodata_json)
  }else{
    exdata = NULL
    vodata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID=PID,
                                         UseExample=UseExample,
                                         Expodata=exdata,
                                         Vocadata=vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Divide exposures and mediators into different groups
#' @description Divide exposures and mediators into different groups according
#'    to the information specified in vocabulary file.
#' @usage XMlists(PID, OutPath)
#' @param PID chr. Program ID. It must be the same with the PID generated
#'    by InitMedt.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", 
#'    the current working directory will be set.It should be noted that the 
#'    slash symbol is "/", not "\". 
#' @details XMlists divides all exposures and mediators into different groups. 
#'    Therefore, the group information(i.e., the "Subgroup" variable) in vocabulary
#'    file is essential for XMlists function. Before using XMlist, the users must 
#'    provide the information in advance and upload it by LoadMedt function.
#' @return A list containing two lists where exposure and mediator variables
#'    were respectively categorized into subgroups in the form of dataframe.
#'    The elements of that list include:
#'    1. "ExpoList": a list containing several dataframes that represent various exposure subgroups.
#'    2. "MediList": a list containing several dataframes that represent various mediator subgroups.
#' @export
#' @examples res <- InitMedt()
#'    res1 <- LoadMedt(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#'    res2 <- XMlists(PID = res$PID)
#' @author Mengyuan Ren, Bin Wang(corresponding author)

XMlists = function(PID,
                   OutPath = "default"){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'XMlists')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/0-XMlists")
  if(!file.exists(path)){dir.create(path)}
  for (i in c(1:length(results$ExpoList))){
    vroom::vroom_write(results$ExpoList[[i]],paste0(path, "/ExpoList",i,".csv"),",")
  }
  for (i in c(1:length(results$MediList))){
    vroom::vroom_write(results$MediList[[i]],paste0(path, "/MediList",i,".csv"),",")
  }
  return(results)
}


#' @title Implement pairwise mediation analyses
#' @description Implement pairwise mediation analyses for each pair of exposure
#'    and mediator.
#' @usage Pairwise(PID, OutPath, VarsY, Family, ...)
#' @param PID chr. Program ID. It must be the same with the PID generated
#'    by InitMedt.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", the 
#'    current working directory will be set.It should be noted that the slash 
#'    symbol is "/", not "\".
#' @param VarsY chr. The outcome variable. Either continuous, binary or count
#'    type is permitted.
#' @param VarsX chr. Exposure variables included in pairwise mediation modelling.
#'    When "default" is specified, all exposure variables in the data will
#'    be used. It should be noted that there is fixed format for the characters
#'    separated with comma and without space, e.g., "X1,X2,X3".
#' @param VarsM chr. Mediator variables included in pairwise mediation modelling.
#'    When "default" is specified, all mediator variables in the data will
#'    be used. It should be noted that there is fixed format for the characters
#'    separated with comma and without space, e.g., "M1,M2,M3".
#' @param VarsC chr. Covariates included in pairwise mediation modelling.
#'    When "default" is specified, all covariates in the data will
#'    be used. It should be noted that there is fixed format for the characters
#'    separated with comma and without space, e.g., "C1,C2".
#' @param Family chr. The error distribution and link function to be used in the
#'    model. Available options include "linear" and "gaussian" for continuous
#'    outcome variables, and "binomial" as well as "poisson" options for binary
#'    and count outcome variables.
#' @param Iter num. The number of iteration times. Default is 500. To get a more stable
#'    result, a minimum iteration of 1,000 is recommended. To obtain more digits
#'    of P value of parameter estimation, a minimum iteration of 5,000 is suggested.
#' @details Pairwise function implements mediation modelling for each pair of exposure
#'    and mediator. Given M exposures and N mediators, an exhaustive rule will be executed 
#'    and M*N pair-wised mediation modelling are fitted. The modelling was realized using 
#'    mediate function in mediation package.
#' @return A list containing one dataframe that contains the pairwise mediation modelling results.
#'    1. "MedtPairWise_Stats": pairwise mediation modelling results.
#' @export
#' @examples res <- InitMedt()
#'    res1 <- LoadMedt(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#'    res2 <- XMlists(PID = res$PID)
#'    res3 <- Pairwise(PID=res$PID, VarsY = "Y1",
#'    VarsX = "default", VarsM = "default", VarsC = "default", Family = "linear",
#'    Iter = 500)
#'    res4 <- Pairwise(PID=res$PID, VarsY = "Y1",
#'    VarsX = "X1,X2,X3", VarsM = "M1,M2,M3", VarsC = "C1", Family = "linear",
#'    Iter = 500)
#' @author Mengyuan Ren, Bin Wang(corresponding author)

Pairwise = function(PID,
                    OutPath = "default",
                    VarsY = "Y1",
                    VarsX = "default",
                    VarsM = "default",
                    VarsC = "default",
                    Family = "linear",
                    Iter = 500){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'Pairwise')
  res = httr::POST(url,
                   body = list(PID=PID,
                               MedtPairWiseVarsY=VarsY,
                               MedtPairWiseVarsX=VarsX,
                               MedtPairWiseVarsM=VarsM,
                               MedtPairWiseVarsC=VarsC,
                               MedtPairWiseFamily=Family,
                               MedtPairWiseIter=Iter
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/1-Pairwise")
  if(!file.exists(path)){dir.create(path)}
  vroom::vroom_write(results$MedtPairWise_Stats,paste0(path, "/Pairwise.modelling.results.csv"),",")
  return(results)
}


#' @title Visualize pairwise mediation modelling result
#' @description Visualize the pairwise mediation result. It should be noted that the
#'    pairwise mediation modelling result has been built by Pairwise function
#'    prior to using it.
#' @usage VizMedtPair(PID, OutPath, ...)
#' @param PID chr. Program ID. It must be the same with the PID generated
#'    by InitMedt.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", 
#'    the current working directory will be set.It should be noted that the 
#'    slash symbol is "/", not "\".
#' @param Brightness chr. Visualization brightness. Available options include
#'    "light" and "dark".
#' @param Pallette chr. Visualization palette. Available options include "default1",
#'    "default2" and "Journal". The "Journal" option provides several journal
#'    preference styles including cell, nature, science, lancet, nejm, and jama.
#' @details VizMedtPair draws a visualized display for pairwise modelling results. 
#'    Piror to using VizMedtPair, make sure that the users have built mediation
#'    models by Pairwise function.
#' @return A list containing two elements where the visualized pairwise modelling plot
#'    as well as the organized plotting data are stored. The elements of that list
#'    include:
#'    1. "plotdata": a dataframe containing the organized plotting data extracted from #'     pairwise mediation modelling result.
#'    2. "plot": a visualized plot for pairwise mediation result.
#' @export
#' @examples res <- InitMedt()
#'    res1 <- LoadMedt(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#'    res2 <- XMlists(PID = res$PID)
#'    res3 <- PairWise(PID=res$PID, VarsY = "Y1",
#'    VarsX = "default", VarsM = "default", VarsC = "default", Family = "linear",
#'    Iter = 500)
#'    res4 <- VizMedtPair(PID=res$PID, Brightness = "Bright",
#'    Pallette = "default1")
#' @author Mengyuan Ren, Bin Wang(corresponding author)

VizMedtPair = function(PID,
                       OutPath = "default",
                       Brightness = "light",
                       Pallette = "default1"){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizMedtPair')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizMedtPairBrightness=Brightness,
                               VizMedtPairPallette=Pallette),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/1-Pairwise")
  if(!file.exists(path)){dir.create(path)}
  vroom::vroom_write(results$plotdata,paste0(path, "/VizPairwise.plotdata.csv"),",")

  jpeg(paste0(path, "/PairWise_plot.jpg"),
       width = 2000,
       height = 1200,
       res = 220)
  grid::grid.draw(results$plot[[1]])
  dev.off()

  return(results)
}


#' @title Expoures dimension reduction
#' @description Implement dimension reduction for exposures.
#' @usage RedX(PID, OutPath, VarsY, Family, ...)
#' @param PID chr. Program ID. It must be the same with the PID generated
#'    by InitMedt.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", 
#'    the current working directory will be set.It should be noted that the 
#'    slash symbol is "/", not "\".
#' @param VarsY chr. The outcome variable. Either continuous, binary or count
#'    type is permitted.
#' @param VarsC chr. Covariates included in mediation modelling.
#'    When "default" is specified, all covariates in the data will
#'    be used. It should be noted that there is fixed format for the characters
#'    separated with comma and without space, e.g., "C1,C2".
#' @param VarsM chr. Mediator variables included in pairwise mediation modelling.
#'    When "default" is specified, all mediator variables in the data will
#'    be used. It should be noted that there is fixed format for the characters
#'    separated with comma and without space, e.g., "M1,M2,M3".
#' @param Method chr. Dimension reduction method. Available options include
#'    "gcdnet" and "mean"(default). "mean" option is recommended when outcome variable
#'    is a binary variable because in some situations low variance of shrinkaged exposure 
#'    variable might obtain in "gcdnet" settings for binary outcome. 
#' @param Folds num. Number of cross validation for gcdnet method. Default is 10.
#' @param Family chr. The error distribution and link function to be used in the
#'    model. Available options include "linear" and "gaussian" for continuous
#'    outcome variables, and "binomial" as well as "poisson" options for binary
#'    and count outcome variables.
#' @param Iter num. The number of iteration times. Default is 500. To get a more stable
#'    result, a minimum iteration of 1,000 is recommended. To obtain more digits
#'    of P value of parameter estimation, a minimum iteration of 5,000 is suggested.
#' @details RedX function provides two alternative methods for exposure dimension 
#'    reduction, including sum method as well as adaptive elastic net method via 
#'    gcdnet package. By default, all exposures will be included for dimension reduction. 
#'    Afterwards, mediation models will be built between given mediators as well as 
#'    shrinkaged exposure variables.
#' @return A list containing three elements where the exposure dimension reduction
#'    variables as well as their mediation modelling results with mediators
#'    are stored. That list include:
#'    1. "MedtRedX_ERSall": a dataframe containing the exposure dimension reduction
#'    result where all exposures are considered as one group (ERS_All).
#'    2. "MedtRedX_ERSlist": a dataframe containing the exposure dimension reduction
#'    results where exposures are shrinkaged in their own subgroups.
#'    3. "MedtRedX_Stats": a dataframe containing the mediation modelling results
#'    where the shrinkaged exposure variables were paired with each mediator provided.
#' @export
#' @examples res <- InitMedt()
#'    res1 <- LoadMedt(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#'    res2 <- XMlists(PID = res$PID)
#'    res3 <- RedX(PID=res$PID, VarsY = "Y1",
#'    VarsC = "default", VarsM = "default", Method = "mean", Folds = 10,
#'    Family = "linear", Iter = 500)
#'    res4 <- RedX(PID=res$PID, VarsY = "Y1",
#'    VarsC = "C1", VarsM = "M1,M2,M3", Method = "mean", Folds = 10,
#'    Family = "linear",Iter = 500)
#' @author Mengyuan Ren, Bin Wang(corresponding author)

RedX = function(PID,
                OutPath = "default",
                VarsY = "Y1",
                VarsC = "default",
                VarsM = "default",
                Method = "mean",
                Folds = 10,
                Family = "linear",
                Iter = 500){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'RedX')
  res = httr::POST(url,
                   body = list(PID=PID,
                               MedtRedXVarsY=VarsY,
                               MedtRedXVarsC=VarsC,
                               MedtRedXVarsM=VarsM,
                               MedtRedXMethod=Method,
                               MedtRedXFolds=Folds,
                               MedtRedXFamily=Family,
                               MedtRedXIter=Iter
                   ),
                   encode = 'json',
                   httr::timeout(600))
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/2.1-RedX")
  if(!file.exists(path)){dir.create(path)}
  vroom::vroom_write(results$MedtRedX_Stats,paste0(path, "/RedX.modelling.results.csv"),",")
  try(vroom::vroom_write(results$MedtRedX_ERSall,paste0(path, "/RedX.MedtRedX_ERSall.csv"),","),silent=TRUE)
  try(vroom::vroom_write(results$MedtRedX_ERSlist,paste0(path, "/RedX.MedtRedX_ERSlist.csv"),","),silent=TRUE)
  return(results)
}


#' @title Mediator dimension reduction
#' @description Implement mediator dimension reduction for mediators.
#' @usage RedM(PID, OutPath, VarsY, Family, ...)
#' @param PID chr. Program ID. It must be the same with the PID generated
#'    by InitMedt.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", 
#'    the current working directory will be set.It should be noted that the 
#'    slash symbol is "/", not "\".
#' @param VarsY chr. The outcome variable. Either continuous, binary or count
#'    type is permitted.
#' @param VarsX chr. Exposure variables included in mediation modelling.
#'    When "default"(recommended) is specified, all exposure variables in the data
#'    will be used. It should be noted that there is fixed format for the characters
#'    separated with comma and without space, e.g., "X1,X2,X3".
#' @param VarsC chr. Covariates included in mediation modelling.
#'    When "default" is specified, all covariates in the data will
#'    be used. It should be noted that there is fixed format for the characters
#'    separated with comma and without space, e.g., "C1,C2".
#' @param Method chr. Dimension reduction method. Available options include
#'    "mean" and "pdm1"(default). "mean" option is recommended when outcome variable
#'    is a binary variable because in some situations error might occur in "pdm1"
#'    settings for binary outcome. 
#' @param Family chr. The error distribution and link function to be used in the
#'    model. Available options include "linear" and "gaussian" for continuous
#'    outcome variables, and "binomial" as well as "poisson" options for binary
#'    and count outcome variables.
#' @param Iter num. The number of iteration times. Default is 500. To get a more stable
#'    result, a minimum iteration of 1,000 is recommended. To obtain more digits
#'    of P value of parameter estimation, a minimum iteration of 5,000 is suggested.
#' @details RedM function provides two alternative methods for mediator dimension 
#'    reduction, including sum method as well as pdm1 method via 
#'    PDM package. By default, all mediators will be included for dimension reduction. 
#'    Afterwards, mediation models will be built between given exposures as well as 
#'    shrinkaged mediator variables.
#' @return A list containing two elements where the mediator dimension reduction
#'    modelling results with exposures are stored. That list include:
#'    1. "MedtRedM_all": a dataframe containing the mediator dimension reduction
#'    result where all mediators are considered as one group and that shrinkaged
#'    mediator is paired and modelled with each exposure.
#'    2. "MedtRedM_list": a dataframe containing the mediator dimension reduction
#'    result where mediators are shrinkaged in their own subgroups, and these
#'    shrinkaged mediators are paired and modelled with each exposure.
#' @export
#' @examples res <- InitMedt()
#'    res1 <- LoadMedt(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#'    res2 <- XMlists(PID = res$PID)
#'    res3 <- RedM(PID=res$PID, VarsY = "Y1", VarsX = "default",
#'    VarsC = "default", Method = "mean", Family = "linear", Iter = 500)
#'    res4 <- RedM(PID=res$PID, VarsY = "Y1", VarsX = "X1,X2,X3",
#'    VarsC = "C1", Method = "mean", Family = "linear", Iter = 500)
#' @author Mengyuan Ren, Bin Wang(corresponding author)

RedM = function(PID,
                OutPath = "default",
                VarsY = "Y1",
                VarsX = "default",
                VarsC = "default",
                Method = "mean",
                Family = "linear",
                Iter = 500){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'RedM')
  res = httr::POST(url,
                   body = list(PID=PID,
                               MedtRedMVarsY=VarsY,
                               MedtRedMVarsX=VarsX,
                               MedtRedMVarsC=VarsC,
                               MedtRedMMethod=Method,
                               MedtRedMFamily=Family,
                               MedtRedMIter=Iter
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/2.2-RedM")
  if(!file.exists(path)){dir.create(path)}
  try(vroom::vroom_write(results$MedtRedM_all,paste0(path, "/RedM-all.mediators.csv"),","),silent=TRUE)
  try(vroom::vroom_write(results$MedtRedM_list,paste0(path, "/RedM-each.mediator.group.csv"),","),silent=TRUE)
  return(results)
}


#' @title Exposure and mediator dimension reduction
#' @description Implement exposure and mediator dimension reduction. It should be
#'    noted that the exposure dimension reduction result has been built by
#'    RedX function prior to using it.
#' @usage RedXM(PID, OutPath, VarsY, Family, ...)
#' @param PID chr. Program ID. It must be the same with the PID generated
#'    by InitMedt.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", 
#'    the current working directory will be set.It should be noted that the 
#'    slash symbol is "/", not "\".
#' @param VarsY chr. The outcome variable. Either continuous, binary or count
#'    type is permitted.
#' @param VarsC chr. Covariates included in mediation modelling.
#'    When "default" is specified, all covariates in the data will
#'    be used. It should be noted that there is fixed format for the characters
#'    separated with comma and without space, e.g., "C1,C2".
#' @param Method chr. Dimension reduction method. Available options include
#'    "mean" and "pdm1"(default). "mean" option is recommended when outcome variable
#'    is a binary variable because in some situations error might occur in "pdm1"
#'    settings for binary outcome.
#' @param Family chr. The error distribution and link function to be used in the
#'    model. Available options include "linear" and "gaussian" for continuous
#'    outcome variables, and "binomial" as well as "poisson" options for binary
#'    and count outcome variables.
#' @param Iter num. The number of iteration times. Default is 500. To get a more stable
#'    result, a minimum iteration of 1,000 is recommended. To obtain more digits
#'    of P value of parameter estimation, a minimum iteration of 5,000 is suggested.
#' @details RedXM function provides two alternative methods for mediator dimension 
#'    reduction, including sum method as well as pdm1 method via PDM package. 
#'    By default, all mediators will be included for dimension reduction. 
#'    Afterwards, mediation models will be built between shrinkaged exposure variables
#'    as well as shrinkaged mediator variables. Prior to using RedXM, make sure that 
#'    RedX function has been executed to obtain shrinkaged exposure variables.
#' @return A list containing two elements where the mediator dimension reduction
#'    modelling results with shrinkaged exposures are stored. That list include:
#'    1. "MedtRedXM_all": a dataframe containing the mediator dimension reduction
#'    result where all mediators are considered as one group and that shrinkaged
#'    mediator is paired and modelled with shrinkaged exposures.
#'    2. "MedtRedXM_list": a dataframe containing the mediator dimension reduction
#'    result where mediators are shrinkaged in their own subgroups, and these
#'    shrinkaged mediators are paired and modelled with shrinkaged exposures.
#' @export
#' @examples res <- InitMedt()
#'    res1 <- LoadMedt(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#'    res2 <- XMlists(PID = res$PID)
#'    res3 <- RedX(PID=res$PID, VarsY = "Y1",
#'    VarsC = "default", VarsM = "default", Method = "mean", Folds = 10,
#'    Family = "linear", Iter = 500)
#'    res4 <- RedXM(PID=res$PID, VarsY = "Y1",
#'    VarsC = "default", Method = "mean", Family = "linear", Iter = 500)
#'    res5 <- RedXM(PID=res$PID, VarsY = "Y1",
#'    VarsC = "C1", Method = "mean", Family = "linear", Iter = 500)
#' @author Mengyuan Ren, Bin Wang(corresponding author)

RedXM = function(PID,
                 OutPath = "default",
                 VarsY = "Y1",
                 VarsC = "default",
                 Method = "mean",
                 Family = "linear",
                 Iter = 500){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'RedXM')
  res = httr::POST(url,
                   body = list(PID=PID,
                               MedtRedXMVarsY=VarsY,
                               MedtRedXMVarsC=VarsC,
                               MedtRedXMMethod=Method,
                               MedtRedXMFamily=Family,
                               MedtRedXMIter=Iter
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/2.3-RedXM")
  if(!file.exists(path)){dir.create(path)}
  try(vroom::vroom_write(results$MedtRedXM_all,paste0(path, "/RedXM-all.mediators.csv"),","),silent=TRUE)
  try(vroom::vroom_write(results$MedtRedXM_list,paste0(path, "/RedXM-each.mediator.group.csv"),","),silent=TRUE)
  return(results)
}


#' @title Visualize RedXM mediation modelling result
#' @description Visualize the RedXM mediation result. It should be noted that
#'    the RedXM mediation modelling result has been built by RedXM function
#'    prior to using it.
#' @usage VizRedXM(PID, OutPath, ...)
#' @param PID chr. Program ID. It must be the same with the PID generated
#'    by InitMedt.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", 
#'    the current working directory will be set.It should be noted that the 
#'    slash symbol is "/", not "\".
#' @param Brightness chr. Visualization brightness. Available options include
#'    "Light" and "Dark".
#' @param Pallette chr. Visualization palette. Available options include "default1",
#'    "default2" and "Journal". The "Journal" option provides several journal
#'    preference styles including cell, nature, science, lancet, nejm, and jama.
#' @details VizRedXM draws a visualized display for RedXM results. 
#'    Piror to using VizMedtPair, make sure that the users have built mediation
#'    models by RedXM function.
#' @return A list containing two elements where the visualized exposure and
#'    mediator dimension reduction plot as well as the organized plotting data
#'    are stored. The elements of that list include:
#'    1. "MedtRedXM_plotadta": a dataframe containing the organized plotting
#'    data extracted from exposure and mediator dimension reduction result.
#'    2. "MedtRedXM_plot": a visualized plot for exposure and mediator
#'    dimension reduction result.
#' @export
#' @examples res <- InitMedt()
#'    res1 <- LoadMedt(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#'    res2 <- XMlists(PID = res$PID)
#'    res3 <- RedX(PID=res$PID, VarsY = "Y1",
#'    VarsC = "default", VarsM = "default", Method = "mean", Folds = 10,
#'    Family = "linear", Iter = 500)
#'    res4 <- RedXM(PID=res$PID, VarsY = "Y1",
#'    VarsC = "default", Method = "mean", Family = "linear", Iter = 500)
#'    res5 <- VizRedXM(PID=res$PID, Brightness = "bright",
#'    Pallette = "nature")
#' @author Mengyuan Ren, Bin Wang(corresponding author)

VizRedXM = function(PID,
                    OutPath = "default",
                    Brightness = "light",
                    Pallette = "default1"){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizRedXM')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizRedXMBrightness=Brightness,
                               VizRedXMPallette=Pallette
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/2.3-RedXM")
  if(!file.exists(path)){dir.create(path)}
  vroom::vroom_write(results$MedtRedXM_plotadta,paste0(path, "/VizMedtRedXM.plotdata.csv"),",")

  ggplot2::ggsave(plot = results$MedtRedXM_plot,
                  filename = stringr::str_c("/RedXM-forest.plot-",Brightness,".",Pallette,"style",".jpg"),
                  path = path,
                  width = 36,
                  height = 18,
                  units = "cm")
  return(results)
}


#' @title Estimate the importance of mediators
#' @description Estimate the importance of mediators.
#' @usage ImptM(PID, OutPath, VarsY, ...)
#' @param PID chr. Program ID. It must be the same with the PID generated
#'    by InitMedt.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", 
#'    the current working directory will be set.It should be noted that the 
#'    slash symbol is "/", not "\".
#' @param VarsY chr. The outcome variable. Either continuous, binary or count
#'    type is permitted.
#' @param VarsX chr. Exposure variables included in estimation procedure.
#'    When "default" is specified, all exposure variables in the data
#'    will be used. The shirnkaged exposure variables are also permitted.
#'    It should be noted that there is fixed format for the characters separated
#'    with comma and without space, e.g., "X1,X2,X3".
#' @param VarsC chr. Covariates included in estimation procedure.
#'    When "default" is specified, all covariates in the data will
#'    be used. It should be noted that there is fixed format for the characters
#'    separated with comma and without space, e.g., "C1,C2".
#' @details ImptM function estimates the importance of mediators among given exposures.
#'    The estimation procedure is mainly realized by the hima function in HIMA package.
#'    ImptM also provides another evaluation method by the bama function in bama package.
#'    The users can search for these packages for further information.
#' @return A list containing four elements where the raw estimation results
#'    as well as the tidy tables for display are stored. The elements of
#'    that list include:
#'    1. "MedtImptM_all": the raw estimation result where the importance of
#'    each mediator was evaluated among whole mediators.
#'    2. "MedtImptM_list": the raw estimation result where the importance of
#'    each mediator was evaluated among each mediator group.
#'    3. "MedtImptM_table1": the tidy table for MedtImptM_all and MedtImptM_list,
#'    where significant estimations (q value <0.2) are expressed with an asterisk
#'    mark (*).
#'    4. "MedtImptM_table2": the tidy table for MedtImptM_all and MedtImptM_list,
#'    where only significant estimations (q value <0.2) are displayed in this table.
#'    MedtImptM_table2 is as same content as MedtImptM_table1.
#' @export
#' @examples res <- InitMedt()
#'    res1 <- LoadMedt(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#'    res2 <- XMlists(PID = res$PID)
#'    res3 <- ImptM(PID = res$PID, VarsY = "Y1",
#'    VarsX = "default", VarsC = "default")
#'    res4 <- ImptM(PID = res$PID, VarsY = "Y1",
#'    VarsX = "X1,X2,X3", VarsC = "C1")
#' @author Mengyuan Ren, Bin Wang(corresponding author)

ImptM = function(PID,
                 OutPath = "default",
                 VarsY = "Y1",
                 VarsX = "default",
                 VarsC = "default"){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'ImptM')
  res = httr::POST(url,
                   body = list(PID=PID,
                               MedtImptMVarsY=VarsY,
                               MedtImptMVarsX=VarsX,
                               MedtImptMVarsC=VarsC
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/2.4-ImptM")
  if(!file.exists(path)){dir.create(path)}
  try(vroom::vroom_write(results$MedtImptM_all,paste0(path, "/ImptM-all.mediators.csv"),","),silent=TRUE)
  try(vroom::vroom_write(results$MedtImptM_list,paste0(path, "/ImptM-each.mediator.group.csv"),","),silent=TRUE)
  try(vroom::vroom_write(results$MedtImptM_table1,paste0(path, "/ImptM-table1.csv"),","),silent=TRUE)
  try(vroom::vroom_write(results$MedtImptM_table2,paste0(path, "/ImptM-table2.csv"),","),silent=TRUE)
  return(results)
}


#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by InitMedt.
#' @details
#' @return
#' @export
#' @examples res <- InitMedt()
#'    res1 <- LoadMedt(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#'    res2 <- XMlists(PID = res$PID)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}

